app/assets/stylesheets/components/_challenge_card.scss
app/views/challenges/_challengee-pending.html.erb
app/views/challenges/_challenger-accepted.html.erb
app/views/challenges/_challenger-pending.html.erb
app/views/challenges/show.html.erb

Edouard, pls check if the screens display the correct challenger/challengee combination thanks

added all challenges views

---

app/assets/stylesheets/components/_challenge_card.scss
app/views/challenges/_challengee-accepted.html.erb
app/views/challenges/_challengee-pending.html.erb
app/views/challenges/_challenger-accepted.html.erb
app/views/challenges/_challenger-pending.html.erb
app/views/challenges/show.html.erb

missing match score 0:0 and centering names in picture card

Challenge card pictures

---

app/views/users/index.html.erb

Wrap lookup operation into a nil guard users#index

---

app/views/users/_users.html.erb
app/views/users/show.html.erb

adjusting comments/thumb sections for new players with no reviews

---

app/views/challenges/_challengee-accepted.html.erb
app/views/challenges/show.html.erb

fix same picture problem on challenge

---

app/assets/stylesheets/components/_back_section.scss
app/views/users/edit.html.erb
app/views/users/show.html.erb

If you want to review it Leo :)

Edit button

---

app/assets/stylesheets/components/_card_index.scss
app/models/user.rb
app/views/users/_users.html.erb
spec/models/user_spec.rb

Should be enough ot start with :)

Indexresponsive

---

app/assets/stylesheets/components/_login_form.scss
app/javascript/plugins/intl.js
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb

Hi @edgr , i believe this is what you wanted. There is one more step - to add country code in the phone number.

Validateintlphone

---

app/javascript/components/tabs.js
app/javascript/plugins/flatpickr.js
app/views/matches/index.html.erb
app/views/matches/new.html.erb
db/seeds.rb

rails db:drop db:create db:migrate db:seed
:)

Fixmatchdate

---

app/controllers/user_reviews_controller.rb

@edgr , we can leave a review, but we need some user story/figma about it. It was designed to review a player after a challenge, so it was clear who is the receiver. But now you want to review a user regardless you have played, so when do you chose the reviewed player?

you can leave a review, but for whom?

---

app/controllers/match_results_controller.rb

@florindiconescu there might be a way to refacto this but not sure. This is simple and easy to play with if we need to change levels.

working locally

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/application.rb
config/initializers/sentry.rb

adding sentry to monitor the errors

---

Gemfile.lock
app/views/devise/registrations/edit.html.erb
app/views/user_steps/step3.html.erb

I have done some updates on my computer, which forced me to update the bundler to be able to open BH as well. Please let me know if it creates any issues to you, but it should be easy to update the bundler if it is required

Photo input trigger gallery

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card_event.scss
app/assets/stylesheets/components/_card_index.scss
app/assets/stylesheets/components/_card_show.scss
app/assets/stylesheets/components/_circle_bar.scss
app/assets/stylesheets/components/_club_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_login_form.scss
app/assets/stylesheets/components/_match_card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_ranking.scss
app/assets/stylesheets/components/_score_input.scss
app/assets/stylesheets/components/_shoutout_card.scss
app/assets/stylesheets/components/_tabs.scss
app/assets/stylesheets/components/_user_review.scss
app/assets/stylesheets/components/_utilities.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_club_show.scss
app/assets/stylesheets/pages/_clubs_index.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_welcome.scss

Revert "changing all font-sizes to rem instead of px"

---

Gemfile
Gemfile.lock
app/controllers/users_controller.rb
app/javascript/components/infinite_scroll.js
app/javascript/packs/application.js
app/models/user.rb
app/queries/search_users.rb
app/views/users/index.html.erb
app/views/users/index.js.erb

Paginate users

---

app/assets/stylesheets/components/_callout_card.scss
app/controllers/callouts_controller.rb
app/views/callouts/index.html.erb
config/locales/en.yml
config/locales/es.yml
config/locales/fr.yml
config/routes.rb
db/migrate/20200206105857_add_status_to_callouts.rb
db/schema.rb

Callouts status

---

app/models/computed_skills_set.rb
app/models/user.rb
db/migrate/20200208184918_add_confirmable_to_devise.rb
db/schema.rb

you need to `rails db:migrate`

Devise confirmation email

---

app/javascript/packs/application.js
app/javascript/plugins/scroll_last_message.js
app/views/chat_rooms/show.html.erb

Revert "fixed"

---

app/controllers/users_controller.rb

With this - all the users will see the same ordering. The ordering will change every 2 hours. No more issues!

refactored the seed for the random ordering on users page

---

app/assets/stylesheets/components/_avatar.scss
app/javascript/components/select_callout_recipients.js
app/javascript/packs/application.js
app/views/callouts/new.html.erb

showing avatar on callouts

---

db/seeds.rb

These were breaking the Seeds generation

quick fix on seeds

---

db/seeds.rb

fixed broken seeds
